### ISSUE TITLE
Backup and Restore Codes

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-ios#20]
**Reported by stephenjudge on 8 Mar 2014 17:44 UTC**
Many sites that offer two factor authentication offer a method to recover access to your account should you loose your authentication device, this is usually SMS authentication or a set of printable codes. However some sites and OTP implementations don't have such a feature and if you loose your authentication device, you loose access to your account.

An example of this is if you add the Google Authenticator plugin to a self-hosted Wordpress blog. The plugin does not provide a secondary method of authentication. In their FAQ there is this question:

"'''Can I create backupcodes'''?

''No, but if you're using an Android smartphone you can replace the Google Authenticator app with [Authenticator Plus](https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus).
It's a really nice app that can import your existing settings, sync between devices and backup/restore using your sd-card.
It's not a free app, but it's well worth the money.''"

This proprietary app, Authenticator Plus, does look very nice and has some nice features, but the most beneficial I think is its ability to backup and restore codes.

This could be a huge addition to FreeOTP and I would like to request that someone considers this feature and looks at a way of implementing it. I am not able to code myself.

**Comment by npmccallum** [comment]
**Modified by stephenjudge on 8 Mar 2014 17:46 UTC**

**Comment by npmccallum** [comment]
**Comment by davidstrauss on 14 Mar 2014 04:32 UTC**
What I would really like is for it to use a standard, FOSS service like Firefox Sync to shuffle data between devices in a secure way.

**Comment by npmccallum** [comment]
**Comment by npmccallum on 28 Mar 2014 18:20 UTC**
Doing is a really great idea. But without encryption support, it is not possible in a secure way. We need to implement encryption first.

**Comment by npmccallum** [comment]
**Comment by patcon on 5 Jan 2015 21:38 UTC**
+1 from me. This is the only feature I really miss. (Having just spent the last 2 hours trying to recover access to a service using 2FA :)

As a work-around in the meantime, there was a review in the android app store that offered a great solution:

https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp&reviewId=Z3A6QU9xcFRPRWNKSE93UTRlVENSall1Wi1FNnY0TVd0SGtDNHhzUEdvVnBoaUZXbHloM2RoVF9NN3NTNFdoSGRoWXZLMWRIcF9hYS1TYlM3MFdteGE2ZHc&hl=en

> After playing with it a bit the only downside is the backup. It needs a proper way to generate a local backup which I could copy to a computer with a truecrypt volume using sftp. To backup you need to use the adb command on your computer. Connect your phone and run: adb backup -f freeotp.bak org.fedorahosted.freeotp That will store the FreeOTP data to the file freeotp.bak. To restore this data, just run: adb restore freeotp.bak

I suppose you need to be decently tech savvy to use it, but it's better than nothing :)

**Comment by npmccallum** [comment]
**Comment by jpl on 16 Jan 2015 02:09 UTC**
YES!  I have some more thoughts about this in ticket #6.

Being able to view the saved tokens would allow manual export to pen/paper, but there's so much more that could be done with import/export/backup/sharing/migrating, all securely, and the crypto isn't that hard.

**Comment by npmccallum** [comment]
**Comment by woi on 17 Jul 2016 18:51 UTC**
Replying to [npmccallum](comment:3):
> Doing is a really great idea. But without encryption support, it is not possible in a secure way. We need to implement encryption first.

I think it would be sufficient to save the backup as an encrypted archive. At least as a first step.
So the user would manually chose to create a backup, then be asked for a password, which then is used to create an AES encrypted zip file (or which ever achieve format is convenient). 
Threema for example backs up like this.

**Comment by npmccallum** [comment]
**Comment by zeevro on 20 Jul 2016 16:12 UTC**
Android can now back up app data to google drive automatically. Adding support for that would be a good idea IMHO.

**Comment by dabura667** [comment]
+1

iOS user. Moving to a new device is always so daunting... would really like to see this included.

export to file, import from file, also "show pairing QR" to recreate the pairing QR for an individual account.

any one of the above would be nice... even an export to unencrypted file option would be better than nothing. Require it to be done by QR codes and I need to have a second device with Freeotp to scan it right then and there. I don't really care much of the method, but I just don't want to have to go through this week long process of deactivating every account one by one spending hours sending in identification documents and other things. Some sites are just easy to reset 2FA, but some aren't.

**Comment by abhibeckert** [comment]
So does this mean if anything goes wrong with the keychain, I will be unable to log into any 2FA authenticated service?

The keychain is not a reliable database in my experience. I've lost keychain data several times as a long time Mac user (most recently just last week, where my whole keychain disapeared and some entries didn't work after restoring from a backup).

**Comment by metbril** [comment]
+1 for bacup/restore.

Some other TOTP apps support this, including OTP Auth: https://itunes.apple.com/us/app/otp-auth-2step-auth-for-pros/id659877384?mt=8

**Comment by maxtannahill** [comment]
+1 for this. Possibly the best option here would be to save the database in a Cryptomator type vault.

**Comment by kennwhite** [comment]
+1 for an encrypted & backup/restore option. [OTPAuth](https://cooperrs.de/otpauth.html) does this and uses an open format, see https://github.com/CooperRS/decrypt-otpauth-files
I've spent two days migrating 30+ accounts to a new device, and this would make a much better UX. Thank you @npmccallum for all the hard work!

**Comment by github-account1111** [comment]
Doesn't this defeat the purpose of 2fa? I.e. something that's local and isolated to the app and your device? It's something only I know + something only I (physically) have, right? Once you have backup functionality, that means that's no longer something only you have. Someone who gets access to your backup can then load it onto their OTP app.

It's not kinda like just having 2 passwords, which is (slightly) better than having one password, but a lot less secure than having an (isolated) OTP app and a password.

**Comment by bobobo1618** [comment]
@github-account1111 I think you're confusing 2FA for "2FA with an immovable, inaccessible secret".

2FA is just "something you know" and "something you have". Even with a backup, unless you _have_ the backup, you can't log in. The second factor is preserved.

A backup feature adds extra attack vectors and gives users a way to potentially shoot themselves in the foot but it doesn't render 2FA useless.

From a more pragmatic standpoint, I think that having a backup feature will be a net benefit for security as it will make 2FA accessible to people who aren't willing to use it without a backup feature (which I suspect is a far larger number of people than those who won't use it _with_ a backup feature). I certainly know people who've been turned off 2FA due to not being able to recover after a lost OTP.

**Comment by throny** [comment]
@github-account1111 @bobobo1618 It should also not be forgotten that in case of a device change a backup and import into the new device is quite practical. Otherwise you would have to reset all OTP, which is a lot of work with a mass of services.

**Comment by orev** [comment]
There is always a trade-off between security and usability. There is a huge risk to user's data if their accounts are broken into because they used a bad password, or they re-used a password from another site that was hacked. Security people can yell forever that people should not re-use passwords across sites, but ultimately that is not within the control of the site owner, and we all know that users mostly ignore this advice. Multi-factor login is one of the only requirements a site owner can enforce that will help to mitigate this issue.

Given the importance of multi-factor to protect against password breaches, it is critical that usability of multi-factor login is low friction as possible. Backup/restore capability is essential to this usability, and yes, it is a trade-off, so each side needs to be evaluated:

- The "no backup" side places everyone at risk, as everyone has a very high likelihood of either getting a new device or losing access to their current one. This means that when a replacement is received, the user is locked out of MFA accounts. They are likely to lose large amounts of data and/or refuse to enable MFA login again.

- "Allowing backups" does place the secret key at some risk, that risk is limited to those who have access to, and are able to decrypt, data on cloud servers (if that is used for backups). If cloud backups are not used, the local systems holding the backups must first be breached for the key material to become compromised. This risk can be greatly reduced by using on-device mechanisms for data encryption.

While I do understand the 'purist' side that says secret keys should never leave the device, it's just not a practical approach. The most secure hard drive is one encased in concrete at the bottom of the ocean, but that scenario does not address the 'A' portion of the 'C I A' triad (Availability). Lack of backup/restore on an MFA app has the same problem.

Finally, site owners have a reputational stake in this issue, so it cannot be completely pushed off onto users by saying that if they did not follow good practices, then they need to accept the consequences. Right or wrong, users whose accounts get hacked will blame the site owner for the hack. If site owners cannot require MFA usage in a low-friction way, then they simply will not offer it as it becomes more of a headache for them to deal with. Not allowing backup/restore creates a large amount of friction.

I believe it is better to address these issues with an open source app, instead of telling people to go get a commercial one.

**Comment by github-account1111** [comment]
@orev when you get a new device or lose your old one you simply use one of the restore codes you have (or were supposed to have) stored in a secure place (like a safe or a wallet), possibly multiple places. Physically. That's the whole point. Something physical + something digital. It's already a backup.

**Comment by justin-stephenson** [comment]
Support for encrypted backup + restore is included in FreeOTP v2.0, closing.

**Comment by bobobo1618** [comment]
For anyone else who might be confused like I was, what they meant by "backup" was "when you back up the entire iPhone, OTPs will be included". There's no mechanism, for example, to back up the OTPs to a file and store them on a flash drive or to transfer OTPs from the iPhone to a new Android device.

**Comment by throny** [comment]
@bobobo1618 Great to know, so its completely useless. 
@justin-stephenson is it planned to implement a crypted export out of the app so it would be usable on a new iPhone without using the Backup and Restore bullshit by Apple?

**Comment by bobobo1618** [comment]
@throny please try to be civil with your comments. Angry hyperbole and swearing isn't going to contribute to a good outcome.

"its completely useless" -> "it isn't what I'd hoped for"
"Backup and Restore bullshit by Apple" -> "Apple's Backup and Restore"

It might also help to elaborate on why Apple's backup and restore isn't a good option for you. To you it might be obvious but to other people here it might not be. If you have privacy concerns or something like that, state them.

Not here to attack you, just trying to make the conversation productive rather than adversarial.

**Comment by throny** [comment]
@bobobo1618 You may be right (I'll edit my last comment) but I'm watching this issue for years now and it's kinda frustrating.

The whole point is: most users (I know) start over with a new phone. They dont use the backup and restore functionality to migrate their phones. It's not a privacy concern, more a usabilty one.

Maybe I'm wrong but the discussion was about getting backups (export/import files, as stated in the most comments above) out of the app. Thats not possible this way as you don't have access to the backup file as its encrypted in the full iOS-Backup.

**Comment by bobobo1618** [comment]
@throny those seem like valid concerns to me. I opened https://github.com/freeotp/freeotp-ios/issues/163. Feel free to add on to it. I don't think it makes sense to continue discussion on this bug as the feature they intended to implement is implemented.
