### ISSUE TITLE
Critical: Cannot access OTPs (which are password locked) after update

### ISSUE THREAD

**Issue by promethial** [freeotp/freeotp-ios#210]
After the latest update, I can't access the OTP's that are locked by password protection. The ones that are not password protected are still accessible. The password seems to be accepted, but the same prompt cycles back up asking for a password. This results in an infinite loop of password prompts and never getting to the OTP.

**Comment by kellerdinan** [comment]
Can’t view code following update, need this for work ASAP!

**Comment by kmeinke** [comment]
I have the same problem

FreeOTP 2.2
iOS 12.4.9 / iPhone5s

Since last update I can not unlock encrypted tokens. 

- After I touch the token to unlock, the enter code screen opens.
- After I enter the code the code screen closes showing the FreeOTP Homescreen
- The app freez 1 sek and crashes to "desktop"
- Just at the moment the code screen opens again
- The code screen closes immediately

Could you please help?

**Comment by kmeinke** [comment]
here is the last crash report.

```
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: org.fedorahosted.freeotp exhausted real (wall clock) time allowance of 10.00 seconds 
```
[FreeOTP-2020-11-21-121728.is.txt](https://github.com/freeotp/freeotp-ios/files/5577512/FreeOTP-2020-11-21-121728.is.txt)

**Comment by kmeinke** [comment]
this workaround still works.
https://github.com/freeotp/freeotp-ios/issues/204#issuecomment-728862912

**Comment by DeadZen** [comment]
Is there a way to disable the password? This is ridiculous.

**Comment by justin-stephenson** [comment]
Could you test and confirm that the following TestFlight build fixes this issue?

https://testflight.apple.com/join/kSkazqq7

**Comment by kmeinke** [comment]
I can’t :( Test flight requires iOS13 I only have 12.4.9

**Comment by dsazonoff** [comment]
> Could you test and confirm that the following TestFlight build fixes this issue?
> 
> 
> 
> https://testflight.apple.com/join/kSkazqq7

No, it doesn't. Face ID is not requested for protected items and codes are not shown.

**Comment by AdamSargon** [comment]
I just tried the app via TestFlight on an iPhone 12 running iOS 14.2.1 and it doesn't work. Nothing happens when I tap on the icon on the left. I don't even get the request to unlock the phone. Tapping on the "share" icon on the right brings me to the "Share Code" page, but nothing happens when I tap on Copy to Clipboard.

**Comment by justin-stephenson** [comment]
I reverted the changes which caused the locked tokens authentication problems, which has worked for some users. Unfortunately if the tokens are still not accessible it appears the OTP keychain item became corrupted in a way that prevents it from being retrieved properly in the keystore. In that case the only solution would be to remove and re-add the token. 

I am going to start providing TestFlight betas builds before upcoming releases are pushed to the App store, to avoid problems like this which aren't caught in my local device testing. Apologies for the troubles this caused.

**Comment by kmeinke** [comment]
Works for me - Thank you very much!

**Comment by seanorama** [comment]
I'm experiencing the same:
- can get codes for items with no lock.
- CAN NOT get code for items with lock.

Biometrics never pop-up. Already gave he app photos and bluetooth access.

FreeOTP 2.3.2 on iPhone 7 wit iOS 15.7.3.
