### ISSUE TITLE
Look at the icon

### ISSUE THREAD

**Issue by AgentMulder006** [freeotp/freeotp-ios#224]
I have one I can which is signed by a lock. I have no idea to open this I can. So I’m not able to enter my email account. Can somebody explain me what to do?
Thank you.

**Comment by rvdse** [comment]
When you add a token, you have the option to _require you to unlock the phone to activate the token_.

If I enable this, there's a small padlock on the icon. When I try to open it, it asks for touch id before showing me the 6-digit code. It seems to work as intended - is this not what happens to you?

**Comment by josejulio** [comment]
I have the same problem. The thing is that it worked before, but now it doesn't ask for anything. I'm supposing something should be  failing silently.

Using FreeOTP 2.2.1 from App Store.

**Comment by justin-stephenson** [comment]
Can you confirm if this issue is still happening for locked tokens in the latest FreeOTP 2.3 ?

**Comment by josejulio** [comment]
Just tried on 2.3 and yes, still an issue.

**Comment by justin-stephenson** [comment]
@josejulio See https://github.com/freeotp/freeotp-ios/issues/225#issuecomment-784464046 for more detail

**Comment by josejulio** [comment]
> can you try adding a new locked token to see if it exhibits the same problem?

Adding a new one works well.

Is there any way to save the others? or should I see them as lost?

**Comment by josejulio** [comment]
> Is there any way to save the others? or should I see them as lost?

From https://github.com/freeotp/freeotp-ios/issues/225#issuecomment-784464046 It looks like they are lost

**Comment by justin-stephenson** [comment]
Please re-open this issue if the problem still persists on the latest FreeOTP version.

**Comment by dleske** [comment]
Following up on that.  The experience I am having is that I had FreeOTP on an old iPhone, I started a new job where they insist on issuing me a new phone, everything transfers over to my new phone, including FreeOTP.  I have two OTP profiles "locked" (requiring me to unlock the phone before I can get the token) and they cannot be unlocked on the new device under FreeOTP 2.3.1.  It's 2.3.1 on the older device as well but I don't know that hasn't updated itself since the mindmeld of old device to new.

I don't know what the underlying issue is but it would be good if I got some error or information message when trying to unlock the token on the new device--I get no response at all, and at first thought the app was broken/frozen.  If I'd had only locked token profiles, that's probably the conclusion I would have reached.

**Comment by eno-afk** [comment]
Hi, same problem over there
I changed phone and now it is impossible to see the code due to my token being locked 
Anyone had ideas?

**Comment by dleske** [comment]
> I changed phone and now it is impossible to see the code due to my token being locked Anyone had ideas?

Unfortunately @eno-afk I think your options are unlock on old phone or use recovery codes.  [This thread](https://github.com/freeotp/freeotp-ios/issues/225#issuecomment-784464046) is referenced above and might provide more background.
